# Generated by Django 4.2.7 on 2024-06-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_image', to='main.media'),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_title', to='goods.aproduct'),
        ),
        migrations.AddField(
            model_name='aproduct',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='main.media'),
        ),
    ]
