# Generated by Django 4.2.7 on 2024-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aproduct',
            name='discpunt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Discount %'),
        ),
    ]
