# Generated by Django 4.2.7 on 2024-06-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_aproduct_discpunt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aproduct',
            old_name='discpunt',
            new_name='discount',
        ),
    ]
